pipeline {
   agent any
    environment{
            AWS_SECRET_ACCESS_KEY     = credentials('aws-secret-key')
            AWS_ACCESS_KEY_ID = credentials('aws-access-key')
    }
   stages {
        stage('Init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('Run') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
